//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worldescape.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Worldescape.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;buildingTiles 000&quot;,
        ///    &quot;ImageUrl&quot;: &quot;ms-appx:///Images/World_Objects/Buildings/buildingTiles_000.png&quot;,
        ///    &quot;Category&quot;: &quot;Buildings&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;buildingTiles 001&quot;,
        ///    &quot;ImageUrl&quot;: &quot;ms-appx:///Images/World_Objects/Buildings/buildingTiles_001.png&quot;,
        ///    &quot;Category&quot;: &quot;Buildings&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;buildingTiles 002&quot;,
        ///    &quot;ImageUrl&quot;: &quot;ms-appx:///Images/World_Objects/Buildings/buildingTiles_002.png&quot;,
        ///    &quot;Category&quot;: &quot;Buildings&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;buildingTiles 003 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConstructAssets {
            get {
                return ResourceManager.GetString("ConstructAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:7034/WorldescapeHub.
        /// </summary>
        internal static string HubService_dev {
            get {
                return ResourceManager.GetString("HubService.dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:7034/WorldescapeHub.
        /// </summary>
        internal static string HubService_prod {
            get {
                return ResourceManager.GetString("HubService.prod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:7034.
        /// </summary>
        internal static string WebService_dev {
            get {
                return ResourceManager.GetString("WebService.dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:7034.
        /// </summary>
        internal static string WebService_prod {
            get {
                return ResourceManager.GetString("WebService.prod", resourceCulture);
            }
        }
    }
}
